//! Implementation of `#[derive(SpecGrammar)]`.
//!
//! Walks a spec enum's variants and emits a `grammar_tags()` inherent method
//! returning `Vec<crate::spec::grammar::GrammarTag>`. Everything the derive
//! reads already lives on the variant:
//!
//! - **name** — the serde tag name: `#[serde(rename = "x")]` if present, else
//!   the ident in `snake_case` (matching serde's `rename_all = "snake_case"`).
//! - **shape** — from the variant's field form (unit / newtype / seq / map).
//! - **fields** — for a `map` variant, each named field's `type`, `required`,
//!   `default`, `default_expr`, and `///` doc. `required` is false for `Option`
//!   fields and for fields with a serde `default`; `default` is emitted (as a
//!   runtime `serde_json::to_value(...)`) only for scalar fields with a serde
//!   default, and `default_expr` (the YAML fragment the default writes as) only
//!   for **non-`Option`** fields whose default is a node — an `Option`'s default
//!   is `None`, which names no node a document could write.
//! - **doc** — the variant's `///`.
//!
//! The four things serde cannot know come from `#[grammar(...)]`:
//! `kind` (mandatory), `output` (default `"scalar"`), `since` (default
//! `SINCE_BASELINE`), and `alt` (an **alternate spelling** the parser accepts
//! that the variant's own field form doesn't express — see [`alt_form`]). The
//! container carries `#[grammar(group = "...")]`.

use quote::quote;
use syn::{Attribute, Data, DeriveInput, Fields, Type, Variant};

pub fn expand(input: DeriveInput) -> Result<proc_macro2::TokenStream, syn::Error> {
    let name = &input.ident;

    let Data::Enum(data) = &input.data else {
        return Err(syn::Error::new_spanned(
            &input,
            "SpecGrammar only supports enums",
        ));
    };

    let group = container_group(&input.attrs)?.ok_or_else(|| {
        syn::Error::new_spanned(
            &input,
            "SpecGrammar needs a container `#[grammar(group = \"...\")]`",
        )
    })?;

    let mut tag_exprs = Vec::new();
    for variant in &data.variants {
        tag_exprs.push(variant_tag(variant, &group)?);
    }

    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();
    Ok(quote! {
        impl #impl_generics #name #ty_generics #where_clause {
            /// Reflect every variant into its grammar descriptor. Generated by
            /// `#[derive(SpecGrammar)]`.
            pub(crate) fn grammar_tags() -> ::std::vec::Vec<crate::spec::grammar::GrammarTag> {
                ::std::vec![ #(#tag_exprs),* ]
            }
        }
    })
}

/// Build the `GrammarTag { .. }` expression for one variant.
fn variant_tag(
    variant: &Variant,
    group: &str,
) -> Result<proc_macro2::TokenStream, syn::Error> {
    let tag_name = serde_name(variant);
    let doc = doc_string(&variant.attrs);
    let VariantGrammar {
        kind,
        output,
        since,
        alt,
    } = variant_grammar(variant)?;

    // `payload` is the grammar type of the single positional value on a
    // `newtype` / `seq` tag (which has no named fields) — the schema layer needs
    // it to know whether `!not <node>`, `!every <uint>`, or `!value <literal>`.
    // `None` for `unit` / `map`.
    let (shape, field_exprs, payload) = match &variant.fields {
        Fields::Unit => ("unit", Vec::new(), None),
        Fields::Named(named) => {
            let mut fields = Vec::new();
            for field in &named.named {
                fields.push(field_expr(field)?);
            }
            ("map", fields, None)
        }
        Fields::Unnamed(unnamed) => {
            let payload = unnamed
                .unnamed
                .first()
                .map(|f| grammar_type(&type_string(&f.ty)).to_owned());
            // A single positional payload. `seq` when it's a list, else `newtype`.
            let is_seq = unnamed
                .unnamed
                .first()
                .map(|f| type_string(&f.ty).starts_with("Vec"))
                .unwrap_or(false);
            (if is_seq { "seq" } else { "newtype" }, Vec::new(), payload)
        }
    };

    let doc_expr = opt_string(doc.clone());
    let payload_expr = opt_string(payload.clone());
    // The canonical form — the variant's own field shape, which is what a
    // generator emits.
    let canonical = quote! {
        crate::spec::grammar::GrammarForm {
            shape: #shape.to_owned(),
            fields: ::std::vec![ #(#field_exprs),* ],
            payload: #payload_expr,
            // Stamped after reflection by `spec::grammar::spec_grammar`, from
            // `check`'s own demand table — serde knows a slot holds a nested
            // expression, not what that expression has to produce.
            payload_output: ::std::option::Option::None,
            // Every reflected form is a slot-fillable expression, so it is
            // legal wherever its group is; only the hand-authored
            // document/weighting rows narrow this.
            scope: ::std::option::Option::None,
            doc: ::std::option::Option::None,
        }
    };
    let alt_expr = alt_form(variant, alt.as_deref(), shape, payload.as_deref())?;
    let forms = match alt_expr {
        Some(alt) => quote! { ::std::vec![ #canonical, #alt ] },
        None => quote! { ::std::vec![ #canonical ] },
    };
    Ok(quote! {
        crate::spec::grammar::GrammarTag {
            name: #tag_name.to_owned(),
            group: #group.to_owned(),
            kind: #kind.to_owned(),
            forms: #forms,
            output: #output.to_owned(),
            projections: ::std::vec::Vec::new(),
            // The conceptual sub-group is editorial and can't be reflected off
            // the type — `spec::grammar::spec_grammar` stamps it from the
            // `CATEGORIES` taxonomy table after reflection.
            category: ::std::string::String::new(),
            doc: #doc_expr,
            since: #since.to_owned(),
            // Every reflected tag is a pure expression node — filesystem
            // access is confined to the hand-authored `import` row.
            host_affecting: false,
        }
    })
}

/// Expand a `#[grammar(alt = "…")]` declaration into the extra
/// [`GrammarForm`](crate::spec::grammar::GrammarForm) it names.
///
/// The alternate spelling of a tag is not visible on its variant — it lives in
/// `NodeSpec::parse_unchecked`'s normalisation pass, which the derive cannot
/// read. So it is *declared* next to the variant, joining `kind` / `output` /
/// `since` as the things serde does not know. Declaring it rather than
/// hand-writing a second table is what keeps the reflected tier drift-proof:
/// `tests/spec_grammar.rs` parses a probe in every declared form and, for the
/// `unary_source` pattern, probes the mirror spelling of *undeclared* tags too,
/// so a form can neither be claimed without existing nor exist without being
/// claimed.
///
/// One value today, because there is one pattern:
///
/// - **`unary_source`** — a one-slot wrapper that accepts its inner expression
///   either bare (`!changed <node>`) or under a single `source:` key
///   (`!changed { source: <node> }`), interchangeably. Implemented by
///   `expr::extract_edge_inner` / `try_dispatch_wrappers`. The derive synthesises
///   whichever of the two the variant *isn't*: a `newtype(node)` variant gains
///   the map form, a `map { source }` variant gains the newtype form. It is an
///   error to declare it on anything else, so the attribute cannot outlive a
///   refactor that changes the variant's shape.
fn alt_form(
    variant: &Variant,
    alt: Option<&str>,
    shape: &str,
    payload: Option<&str>,
) -> Result<Option<proc_macro2::TokenStream>, syn::Error> {
    let Some(alt) = alt else {
        return Ok(None);
    };
    if alt != "unary_source" {
        return Err(syn::Error::new_spanned(
            variant,
            format!("unknown `#[grammar(alt = \"{alt}\")]` — the only pattern is `unary_source`"),
        ));
    }
    let bad = |detail: &str| {
        syn::Error::new_spanned(
            variant,
            format!(
                "`#[grammar(alt = \"unary_source\")]` on `{}`: {detail}. The pattern names a \
                 wrapper that accepts `!tag <node>` and `!tag {{ source: <node> }}` \
                 interchangeably, so the variant must be one of those two shapes.",
                variant.ident
            ),
        )
    };
    match shape {
        // A `newtype(node)` variant also parses under a lone `source:` key.
        "newtype" => {
            if payload != Some("node") {
                return Err(bad(&format!(
                    "the variant is a newtype carrying `{}`, not `node`",
                    payload.unwrap_or("nothing")
                )));
            }
            let doc = SOURCE_MAP_DOC;
            Ok(Some(quote! {
                crate::spec::grammar::GrammarForm {
                    shape: "map".to_owned(),
                    fields: ::std::vec![crate::spec::grammar::GrammarField {
                        name: "source".to_owned(),
                        ty: "node".to_owned(),
                        required: true,
                        default: ::std::option::Option::None,
                        // The keyed spelling of a `newtype` wrapper: its lone
                        // slot is the tag's payload, which is required.
                        default_expr: ::std::option::Option::None,
                        node_output: ::std::option::Option::None,
                        doc: ::std::option::Option::Some(#SOURCE_FIELD_DOC.to_owned()),
                    }],
                    payload: ::std::option::Option::None,
                    payload_output: ::std::option::Option::None,
                    scope: ::std::option::Option::None,
                    doc: ::std::option::Option::Some(#doc.to_owned()),
                }
            }))
        }
        // A `map { source }` variant also parses with the inner written bare.
        "map" => {
            let named = match &variant.fields {
                Fields::Named(named) => named,
                _ => unreachable!("shape == map implies named fields"),
            };
            let only_source = named.named.len() == 1
                && named
                    .named
                    .first()
                    .and_then(|f| f.ident.as_ref())
                    .is_some_and(|i| i == "source");
            if !only_source {
                return Err(bad("the variant's body is not a lone `source` field"));
            }
            let doc = BARE_INNER_DOC;
            Ok(Some(quote! {
                crate::spec::grammar::GrammarForm {
                    shape: "newtype".to_owned(),
                    fields: ::std::vec::Vec::new(),
                    payload: ::std::option::Option::Some("node".to_owned()),
                    payload_output: ::std::option::Option::None,
                    scope: ::std::option::Option::None,
                    doc: ::std::option::Option::Some(#doc.to_owned()),
                }
            }))
        }
        other => Err(bad(&format!("the variant is a `{other}` tag"))),
    }
}

/// Prose for the synthesised `{ source: … }` spelling of a `newtype` wrapper.
const SOURCE_MAP_DOC: &str =
    "The keyed spelling: the same inner expression written under a lone \
     `source:` key. Equivalent to the bare form, and the one to reach for when \
     YAML forbids the bare one — a tag cannot carry another tag directly, so an \
     inner that is itself a `!tag` has to be keyed (or spelled as a single-key \
     map).";

/// Prose for the synthesised bare spelling of a `map { source }` wrapper.
const BARE_INNER_DOC: &str =
    "The bare spelling: the inner expression written directly as the tag's \
     payload, with no `source:` key. Equivalent to the keyed form. Reachable in \
     YAML only when the inner needs no tag of its own (a bare word like \
     `close`), since YAML forbids two tags on one node — the JSON bridge form \
     has no such limit.";

/// Prose for the `source` field of a synthesised keyed spelling.
const SOURCE_FIELD_DOC: &str = "The wrapped expression.";

/// Build the `GrammarField { .. }` expression for one named field.
fn field_expr(field: &syn::Field) -> Result<proc_macro2::TokenStream, syn::Error> {
    let name = field.ident.as_ref().expect("named field").to_string();
    let doc = doc_string(&field.attrs);
    let doc_expr = opt_string(doc);

    let ty_str = type_string(&field.ty);
    let is_option = ty_str.starts_with("Option");
    let grammar_ty = grammar_type(&ty_str);
    let is_scalar = matches!(grammar_ty, "uint" | "positive_uint" | "number" | "str" | "bool");

    let default_kind = serde_default(&field.attrs)?;
    let required = !is_option && matches!(default_kind, SerdeDefault::None);

    // Emit a literal default value only for scalar fields with a serde default.
    let default_value = match (&default_kind, is_scalar) {
        (SerdeDefault::Fn(path), true) => {
            let path = default_path(field, path)?;
            quote! { ::serde_json::to_value(#path()).ok() }
        }
        (SerdeDefault::Bare, true) => {
            let ty = &field.ty;
            quote! { ::serde_json::to_value(<#ty as ::std::default::Default>::default()).ok() }
        }
        _ => quote! { ::std::option::Option::None },
    };

    // A non-scalar default is a *node* (`!ema`'s `source` is a `!close` leaf,
    // a selection rule's `of` an `!everything`), which no JSON literal can
    // carry — so it goes to `default_expr` as the YAML fragment writing it
    // would produce. The value is spelled by `grammar::default_expr_of` at run
    // time, off the default's own `Debug`, so this cannot drift from what the
    // default fn returns.
    //
    // An `Option` field is excluded deliberately, and this is the whole split
    // the field exists to make: its default is Rust `None` — "the key is
    // absent" — which names no node. That is the honest answer for the
    // blessed-series `source:` on a candle leaf, where omission means "the
    // strategy's own series" and no tag says that.
    let default_expr = match (&default_kind, is_scalar, is_option) {
        (SerdeDefault::Fn(path), false, false) => {
            let path = default_path(field, path)?;
            quote! { crate::spec::grammar::default_expr_of(#path()) }
        }
        (SerdeDefault::Bare, false, false) => {
            let ty = &field.ty;
            quote! {
                crate::spec::grammar::default_expr_of(
                    <#ty as ::std::default::Default>::default()
                )
            }
        }
        _ => quote! { ::std::option::Option::None },
    };

    Ok(quote! {
        crate::spec::grammar::GrammarField {
            name: #name.to_owned(),
            ty: #grammar_ty.to_owned(),
            required: #required,
            default: #default_value,
            default_expr: #default_expr,
            // Stamped after reflection — see `payload_output` above.
            node_output: ::std::option::Option::None,
            doc: #doc_expr,
        }
    })
}

/// Parse a `#[serde(default = "path")]` payload into the path to call.
fn default_path(field: &syn::Field, path: &str) -> Result<syn::Path, syn::Error> {
    syn::parse_str(path)
        .map_err(|e| syn::Error::new_spanned(field, format!("bad serde default path: {e}")))
}

/// Map a Rust field type onto the grammar's closed type vocabulary.
fn grammar_type(ty_str: &str) -> &'static str {
    // Peel `Option<...>` / `Box<...>` wrappers to look at the inner type.
    let inner = strip_wrappers(ty_str);
    if inner.contains("NodeSpec") {
        if inner.starts_with("Vec") {
            "node_list"
        } else {
            "node"
        }
    } else if inner.starts_with("Vec<String>") || inner.starts_with("Vec<str>") {
        // A raw list of names, e.g. `!all_of [BTC, ETH]` (`UniverseSpec`).
        "str_list"
    } else if inner.starts_with("Vec<Real>") || inner.starts_with("Vec<f64>") {
        "number_list"
    } else if inner.contains("SelectionRuleSpec") {
        "selection"
    } else if inner.contains("ValueLit") {
        // A constant leaf: number | string | bool | list-of-number.
        "literal"
    } else if inner.contains("MatchCase") {
        "match_cases"
    } else if inner.contains("AnyStrategyRef") {
        "strategy"
    } else if inner.contains("StrOperand") {
        "str_operand"
    } else if inner == "NonZeroUsize" {
        // Periods and window lengths. Distinct from `uint` because serde
        // rejects 0 at *parse*, so the generated schema can say `minimum: 1`
        // instead of deferring to a construction-time assert.
        "positive_uint"
    } else if inner == "usize" {
        "uint"
    } else if inner == "Real" || inner == "f64" {
        "number"
    } else if inner == "String" || inner == "str" {
        "str"
    } else if inner == "bool" {
        "bool"
    } else {
        // Fallback: unknown leaf types are rare and downstream-inert. Keep the
        // descriptor honest rather than guessing a scalar.
        "other"
    }
}

/// Strip `Option< >` and `Box< >` wrappers (repeatedly) from a stringified type.
fn strip_wrappers(ty_str: &str) -> String {
    let mut s = ty_str.replace(' ', "");
    loop {
        if let Some(rest) = s.strip_prefix("Option<").and_then(|r| r.strip_suffix('>')) {
            s = rest.to_string();
        } else if let Some(rest) = s.strip_prefix("Box<").and_then(|r| r.strip_suffix('>')) {
            s = rest.to_string();
        } else {
            break;
        }
    }
    s
}

/// A type rendered back to a compact string (`quote` inserts spaces we keep for
/// prefix checks like `Option` / `Vec`).
fn type_string(ty: &Type) -> String {
    quote!(#ty).to_string()
}

/// serde field-default state.
enum SerdeDefault {
    None,
    Bare,
    Fn(String),
}

/// Parse `#[serde(default)]` / `#[serde(default = "fn")]` off a field.
fn serde_default(attrs: &[Attribute]) -> Result<SerdeDefault, syn::Error> {
    let mut out = SerdeDefault::None;
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("default") {
                if meta.input.peek(syn::Token![=]) {
                    let value = meta.value()?;
                    let lit: syn::LitStr = value.parse()?;
                    out = SerdeDefault::Fn(lit.value());
                } else {
                    out = SerdeDefault::Bare;
                }
            } else if meta.input.peek(syn::token::Paren) {
                // e.g. `serde(rename_all(...))` — consume the group, ignore.
                let _ = meta.parse_nested_meta(|_| Ok(()));
            } else if meta.input.peek(syn::Token![=]) {
                // e.g. `serde(rename = "x")` — consume the value, ignore.
                let _ = meta.value()?.parse::<syn::Lit>();
            }
            Ok(())
        })?;
    }
    Ok(out)
}

/// The serde tag name: `#[serde(rename = "x")]` if present, else `snake_case`
/// of the ident (matching the enums' `rename_all = "snake_case"`).
fn serde_name(variant: &Variant) -> String {
    for attr in &variant.attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let mut rename = None;
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("rename") {
                if let Ok(value) = meta.value()
                    && let Ok(lit) = value.parse::<syn::LitStr>()
                {
                    rename = Some(lit.value());
                }
            } else if meta.input.peek(syn::Token![=]) {
                let _ = meta.value()?.parse::<syn::Lit>();
            }
            Ok(())
        });
        if let Some(name) = rename {
            return name;
        }
    }
    snake_case(&variant.ident.to_string())
}

/// PascalCase -> snake_case, matching serde's convention: `_` before every
/// uppercase after the first, then lowercase. `MacdLine` -> `macd_line`,
/// `DmiPlusDi` -> `dmi_plus_di`, `ZScore` -> `z_score`.
fn snake_case(ident: &str) -> String {
    let mut out = String::new();
    for (i, ch) in ident.chars().enumerate() {
        if ch.is_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// Parse the container-level `#[grammar(group = "...")]`.
fn container_group(attrs: &[Attribute]) -> Result<Option<String>, syn::Error> {
    let mut group = None;
    for attr in attrs {
        if !attr.path().is_ident("grammar") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("group") {
                let lit: syn::LitStr = meta.value()?.parse()?;
                group = Some(lit.value());
                Ok(())
            } else {
                Err(meta.error("expected `group`"))
            }
        })?;
    }
    Ok(group)
}

/// What `#[grammar(...)]` declares on one variant — everything about a tag that
/// serde's own definition cannot express.
struct VariantGrammar {
    kind: String,
    output: String,
    /// A token expression, because the default reads the `SINCE_BASELINE` const
    /// rather than being a literal.
    since: proc_macro2::TokenStream,
    /// The named alternate-spelling pattern, if any. See [`alt_form`].
    alt: Option<String>,
}

/// Parse the per-variant
/// `#[grammar(kind = "...", output = "...", since = "...", alt = "...")]`.
/// `kind` is mandatory; `output` defaults to `"scalar"`; `since` defaults to
/// the crate's `SINCE_BASELINE` (emitted as a token that reads the const); `alt`
/// defaults to none.
fn variant_grammar(variant: &Variant) -> Result<VariantGrammar, syn::Error> {
    let mut kind = None;
    let mut output = None;
    let mut since = None;
    let mut alt = None;
    for attr in &variant.attrs {
        if !attr.path().is_ident("grammar") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("kind") {
                kind = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.path.is_ident("output") {
                output = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.path.is_ident("since") {
                since = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.path.is_ident("alt") {
                alt = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else {
                return Err(meta.error("expected `kind`, `output`, `since`, or `alt`"));
            }
            Ok(())
        })?;
    }
    let kind = kind.ok_or_else(|| {
        syn::Error::new_spanned(
            variant,
            format!(
                "variant `{}` needs `#[grammar(kind = \"...\")]` \
                 (source | indicator | operator | predicate | function | selection)",
                variant.ident
            ),
        )
    })?;
    let output = output.unwrap_or_else(|| "scalar".to_string());
    let since = match since {
        Some(v) => quote! { #v },
        None => quote! { crate::spec::grammar::SINCE_BASELINE },
    };
    Ok(VariantGrammar {
        kind,
        output,
        since,
        alt,
    })
}

/// Concatenate a run of `#[doc = "..."]` attrs into one trimmed string.
fn doc_string(attrs: &[Attribute]) -> Option<String> {
    let mut lines: Vec<String> = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        if let syn::Meta::NameValue(nv) = &attr.meta
            && let syn::Expr::Lit(syn::ExprLit {
                lit: syn::Lit::Str(s),
                ..
            }) = &nv.value
        {
            lines.push(s.value().trim().to_string());
        }
    }
    if lines.is_empty() {
        return None;
    }
    let joined = lines.join(" ").split_whitespace().collect::<Vec<_>>().join(" ");
    let joined = strip_doc_links(&joined);
    if joined.is_empty() { None } else { Some(joined) }
}

/// Strip rustdoc intra-doc / markdown links from prose so the descriptor carries
/// clean **presentation** text, not doc-source markup. A `///` comment is
/// authored for rustdoc, but the same string is the end-user reference every
/// grammar consumer renders (the CLI catalogue, editor tooling, docs), where
/// `` [`crate::foo::Bar`] `` reads as noise.
///
/// Two forms are rewritten to their display text (the final `::` path segment
/// for a code-span link): the shortcut `` [`Bar`] `` and the explicit
/// `` [`Bar`](target) `` / `[text](url)`. A **bare** `[…]` with neither a code
/// span nor a `(…)` target is left untouched — it's prose (`[0, period - 1]`),
/// not a link.
fn strip_doc_links(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut rest = s;
    while let Some(open) = rest.find('[') {
        out.push_str(&rest[..open]);
        let tail = &rest[open..]; // starts at '['
        let Some(close_rel) = tail.find(']') else {
            // No closing bracket at all — copy the '[' and move on.
            out.push('[');
            rest = &tail[1..];
            continue;
        };
        let inner = &tail[1..close_rel];
        let after = &tail[close_rel + 1..]; // just past ']'
        let is_code_span = inner.len() >= 2 && inner.starts_with('`') && inner.ends_with('`');
        let has_target = after.starts_with('(');
        if is_code_span || has_target {
            let text = inner.trim_matches('`');
            // Rustdoc paths (`crate::a::B`) render best as their final segment.
            let display = text.rsplit("::").next().unwrap_or(text);
            out.push_str(display);
            // Consume a trailing `(target)` if this was an explicit link.
            if has_target && let Some(pclose) = after.find(')') {
                rest = &after[pclose + 1..];
                continue;
            }
            rest = after;
        } else {
            // A bare `[…]` in prose — not a link. Keep it verbatim.
            out.push('[');
            rest = &tail[1..];
        }
    }
    out.push_str(rest);
    out
}

/// `Some(s)` -> `Some(s.to_owned())`, `None` -> `None`, as tokens.
fn opt_string(value: Option<String>) -> proc_macro2::TokenStream {
    match value {
        Some(s) => quote! { ::std::option::Option::Some(#s.to_owned()) },
        None => quote! { ::std::option::Option::None },
    }
}
