//! Implementation of `#[derive(SpecGrammar)]`.
//!
//! Walks a spec enum's variants and emits a `grammar_tags()` inherent method
//! returning `Vec<crate::spec::grammar::GrammarTag>`. Everything the derive
//! reads already lives on the variant:
//!
//! - **name** — the serde tag name: `#[serde(rename = "x")]` if present, else
//!   the ident in `snake_case` (matching serde's `rename_all = "snake_case"`).
//! - **shape** — from the variant's field form (unit / newtype / seq / map).
//! - **fields** — for a `map` variant, each named field's `type`, `required`,
//!   `default`, and `///` doc. `required` is false for `Option` fields and for
//!   fields with a serde `default`; `default` is emitted (as a runtime
//!   `serde_json::to_value(...)`) only for scalar fields with a serde default.
//! - **doc** — the variant's `///`.
//!
//! The three fields serde cannot know come from `#[grammar(...)]`:
//! `kind` (mandatory), `output` (default `"scalar"`), `since` (default
//! `SINCE_BASELINE`). The container carries `#[grammar(group = "...")]`.

use quote::quote;
use syn::{Attribute, Data, DeriveInput, Fields, Type, Variant};

pub fn expand(input: DeriveInput) -> Result<proc_macro2::TokenStream, syn::Error> {
    let name = &input.ident;

    let Data::Enum(data) = &input.data else {
        return Err(syn::Error::new_spanned(
            &input,
            "SpecGrammar only supports enums",
        ));
    };

    let group = container_group(&input.attrs)?.ok_or_else(|| {
        syn::Error::new_spanned(
            &input,
            "SpecGrammar needs a container `#[grammar(group = \"...\")]`",
        )
    })?;

    let mut tag_exprs = Vec::new();
    for variant in &data.variants {
        tag_exprs.push(variant_tag(variant, &group)?);
    }

    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();
    Ok(quote! {
        impl #impl_generics #name #ty_generics #where_clause {
            /// Reflect every variant into its grammar descriptor. Generated by
            /// `#[derive(SpecGrammar)]`.
            pub(crate) fn grammar_tags() -> ::std::vec::Vec<crate::spec::grammar::GrammarTag> {
                ::std::vec![ #(#tag_exprs),* ]
            }
        }
    })
}

/// Build the `GrammarTag { .. }` expression for one variant.
fn variant_tag(
    variant: &Variant,
    group: &str,
) -> Result<proc_macro2::TokenStream, syn::Error> {
    let tag_name = serde_name(variant);
    let doc = doc_string(&variant.attrs);
    let (kind, output, since) = variant_grammar(variant)?;

    let (shape, field_exprs) = match &variant.fields {
        Fields::Unit => ("unit", Vec::new()),
        Fields::Named(named) => {
            let mut fields = Vec::new();
            for field in &named.named {
                fields.push(field_expr(field)?);
            }
            ("map", fields)
        }
        Fields::Unnamed(unnamed) => {
            // A single positional payload. `seq` when it's a list, else `newtype`.
            let is_seq = unnamed
                .unnamed
                .first()
                .map(|f| type_string(&f.ty).starts_with("Vec"))
                .unwrap_or(false);
            (if is_seq { "seq" } else { "newtype" }, Vec::new())
        }
    };

    let doc_expr = opt_string(doc);
    Ok(quote! {
        crate::spec::grammar::GrammarTag {
            name: #tag_name.to_owned(),
            group: #group.to_owned(),
            kind: #kind.to_owned(),
            shape: #shape.to_owned(),
            fields: ::std::vec![ #(#field_exprs),* ],
            output: #output.to_owned(),
            projections: ::std::vec::Vec::new(),
            doc: #doc_expr,
            since: #since.to_owned(),
        }
    })
}

/// Build the `GrammarField { .. }` expression for one named field.
fn field_expr(field: &syn::Field) -> Result<proc_macro2::TokenStream, syn::Error> {
    let name = field.ident.as_ref().expect("named field").to_string();
    let doc = doc_string(&field.attrs);
    let doc_expr = opt_string(doc);

    let ty_str = type_string(&field.ty);
    let is_option = ty_str.starts_with("Option");
    let grammar_ty = grammar_type(&ty_str);
    let is_scalar = matches!(grammar_ty, "uint" | "number" | "str" | "bool");

    let default_kind = serde_default(&field.attrs)?;
    let required = !is_option && matches!(default_kind, SerdeDefault::None);

    // Emit a literal default value only for scalar fields with a serde default.
    // Node-typed defaults are blessed-series fallbacks, not literals -> null.
    let default_expr = match (&default_kind, is_scalar) {
        (SerdeDefault::Fn(path), true) => {
            let path: syn::Path = syn::parse_str(path)
                .map_err(|e| syn::Error::new_spanned(field, format!("bad serde default path: {e}")))?;
            quote! { ::serde_json::to_value(#path()).ok() }
        }
        (SerdeDefault::Bare, true) => {
            let ty = &field.ty;
            quote! { ::serde_json::to_value(<#ty as ::std::default::Default>::default()).ok() }
        }
        _ => quote! { ::std::option::Option::None },
    };

    Ok(quote! {
        crate::spec::grammar::GrammarField {
            name: #name.to_owned(),
            ty: #grammar_ty.to_owned(),
            required: #required,
            default: #default_expr,
            doc: #doc_expr,
        }
    })
}

/// Map a Rust field type onto the grammar's closed type vocabulary.
fn grammar_type(ty_str: &str) -> &'static str {
    // Peel `Option<...>` / `Box<...>` wrappers to look at the inner type.
    let inner = strip_wrappers(ty_str);
    if inner.contains("NodeSpec") {
        if inner.starts_with("Vec") {
            "node_list"
        } else {
            "node"
        }
    } else if inner.contains("SelectionRuleSpec") {
        "selection"
    } else if inner.contains("MatchCase") {
        "match_cases"
    } else if inner.contains("AnyStrategyRef") {
        "strategy"
    } else if inner.contains("StrOperand") {
        "str_operand"
    } else if inner == "usize" {
        "uint"
    } else if inner == "Real" || inner == "f64" {
        "number"
    } else if inner == "String" || inner == "str" {
        "str"
    } else if inner == "bool" {
        "bool"
    } else {
        // Fallback: unknown leaf types are rare and downstream-inert. Keep the
        // descriptor honest rather than guessing a scalar.
        "other"
    }
}

/// Strip `Option< >` and `Box< >` wrappers (repeatedly) from a stringified type.
fn strip_wrappers(ty_str: &str) -> String {
    let mut s = ty_str.replace(' ', "");
    loop {
        if let Some(rest) = s.strip_prefix("Option<").and_then(|r| r.strip_suffix('>')) {
            s = rest.to_string();
        } else if let Some(rest) = s.strip_prefix("Box<").and_then(|r| r.strip_suffix('>')) {
            s = rest.to_string();
        } else {
            break;
        }
    }
    s
}

/// A type rendered back to a compact string (`quote` inserts spaces we keep for
/// prefix checks like `Option` / `Vec`).
fn type_string(ty: &Type) -> String {
    quote!(#ty).to_string()
}

/// serde field-default state.
enum SerdeDefault {
    None,
    Bare,
    Fn(String),
}

/// Parse `#[serde(default)]` / `#[serde(default = "fn")]` off a field.
fn serde_default(attrs: &[Attribute]) -> Result<SerdeDefault, syn::Error> {
    let mut out = SerdeDefault::None;
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("default") {
                if meta.input.peek(syn::Token![=]) {
                    let value = meta.value()?;
                    let lit: syn::LitStr = value.parse()?;
                    out = SerdeDefault::Fn(lit.value());
                } else {
                    out = SerdeDefault::Bare;
                }
            } else if meta.input.peek(syn::token::Paren) {
                // e.g. `serde(rename_all(...))` — consume the group, ignore.
                let _ = meta.parse_nested_meta(|_| Ok(()));
            } else if meta.input.peek(syn::Token![=]) {
                // e.g. `serde(rename = "x")` — consume the value, ignore.
                let _ = meta.value()?.parse::<syn::Lit>();
            }
            Ok(())
        })?;
    }
    Ok(out)
}

/// The serde tag name: `#[serde(rename = "x")]` if present, else `snake_case`
/// of the ident (matching the enums' `rename_all = "snake_case"`).
fn serde_name(variant: &Variant) -> String {
    for attr in &variant.attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let mut rename = None;
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("rename") {
                if let Ok(value) = meta.value()
                    && let Ok(lit) = value.parse::<syn::LitStr>()
                {
                    rename = Some(lit.value());
                }
            } else if meta.input.peek(syn::Token![=]) {
                let _ = meta.value()?.parse::<syn::Lit>();
            }
            Ok(())
        });
        if let Some(name) = rename {
            return name;
        }
    }
    snake_case(&variant.ident.to_string())
}

/// PascalCase -> snake_case, matching serde's convention: `_` before every
/// uppercase after the first, then lowercase. `MacdLine` -> `macd_line`,
/// `DmiPlusDi` -> `dmi_plus_di`, `ZScore` -> `z_score`.
fn snake_case(ident: &str) -> String {
    let mut out = String::new();
    for (i, ch) in ident.chars().enumerate() {
        if ch.is_uppercase() {
            if i != 0 {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// Parse the container-level `#[grammar(group = "...")]`.
fn container_group(attrs: &[Attribute]) -> Result<Option<String>, syn::Error> {
    let mut group = None;
    for attr in attrs {
        if !attr.path().is_ident("grammar") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("group") {
                let lit: syn::LitStr = meta.value()?.parse()?;
                group = Some(lit.value());
                Ok(())
            } else {
                Err(meta.error("expected `group`"))
            }
        })?;
    }
    Ok(group)
}

/// Parse the per-variant `#[grammar(kind = "...", output = "...", since = "...")]`.
/// `kind` is mandatory; `output` defaults to `"scalar"`; `since` defaults to
/// the crate's `SINCE_BASELINE` (emitted as a token that reads the const).
fn variant_grammar(
    variant: &Variant,
) -> Result<(String, String, proc_macro2::TokenStream), syn::Error> {
    let mut kind = None;
    let mut output = None;
    let mut since = None;
    for attr in &variant.attrs {
        if !attr.path().is_ident("grammar") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("kind") {
                kind = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.path.is_ident("output") {
                output = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else if meta.path.is_ident("since") {
                since = Some(meta.value()?.parse::<syn::LitStr>()?.value());
            } else {
                return Err(meta.error("expected `kind`, `output`, or `since`"));
            }
            Ok(())
        })?;
    }
    let kind = kind.ok_or_else(|| {
        syn::Error::new_spanned(
            variant,
            format!(
                "variant `{}` needs `#[grammar(kind = \"...\")]` \
                 (source | indicator | operator | predicate | function | selection)",
                variant.ident
            ),
        )
    })?;
    let output = output.unwrap_or_else(|| "scalar".to_string());
    let since = match since {
        Some(v) => quote! { #v },
        None => quote! { crate::spec::grammar::SINCE_BASELINE },
    };
    Ok((kind, output, since))
}

/// Concatenate a run of `#[doc = "..."]` attrs into one trimmed string.
fn doc_string(attrs: &[Attribute]) -> Option<String> {
    let mut lines: Vec<String> = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        if let syn::Meta::NameValue(nv) = &attr.meta
            && let syn::Expr::Lit(syn::ExprLit {
                lit: syn::Lit::Str(s),
                ..
            }) = &nv.value
        {
            lines.push(s.value().trim().to_string());
        }
    }
    if lines.is_empty() {
        return None;
    }
    let joined = lines.join(" ").split_whitespace().collect::<Vec<_>>().join(" ");
    if joined.is_empty() { None } else { Some(joined) }
}

/// `Some(s)` -> `Some(s.to_owned())`, `None` -> `None`, as tokens.
fn opt_string(value: Option<String>) -> proc_macro2::TokenStream {
    match value {
        Some(s) => quote! { ::std::option::Option::Some(#s.to_owned()) },
        None => quote! { ::std::option::Option::None },
    }
}
