//! `#[derive(SpecRaw)]` — emit the externally-tagged deserialization twin of a
//! `#[serde(try_from = …)]` spec enum, plus the mechanical `From` back.
//!
//! `NodeSpec` carries `#[serde(try_from = "serde_norway::Value")]`, so it
//! cannot also carry serde's *derived* externally-tagged deserialization; that
//! used to live on a ~1,650-line hand-maintained mirror (`NodeSpecRaw` plus a
//! variant-by-variant `From` impl), guarded only by tests that regex-scraped
//! `expr.rs`'s source text — the weakest guard shape in the suite, and one a
//! formatting change could break. A diff of the two enum bodies (docs and
//! `#[grammar]` attrs stripped) confirmed the mirror byte-mechanical before
//! this derive replaced it.
//!
//! The emission: an enum named `<Ident>Raw` with every variant and field
//! cloned and **only the `#[serde(...)]` attributes** carried over (doc
//! comments and `#[grammar(...)]` dropped), deriving `Debug + Deserialize`
//! under `rename_all = "snake_case"` + `deny_unknown_fields`, plus
//! `impl From<<Ident>Raw> for <Ident>` moving each field across. Child fields
//! stay `Box<<Ident>>` — the recursion re-enters the host enum's own
//! `TryFrom`, which is what runs the pre-parse rewrites at every level — so
//! the `From` is a plain move, never a conversion.
//!
//! A new variant now exists the moment it is written, in both the typed enum
//! and its deserialization, with the serde attributes stated once.

use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Fields};

/// Keep only the `#[serde(...)]` attributes of `attrs` — the ones that shape
/// deserialization. Docs are presentation (the grammar descriptor carries
/// them) and `#[grammar(...)]` is the descriptor derive's input; neither
/// belongs on the deserialization twin.
fn serde_attrs(attrs: &[syn::Attribute]) -> Vec<&syn::Attribute> {
    attrs
        .iter()
        .filter(|a| a.path().is_ident("serde"))
        .collect()
}

pub(crate) fn expand(input: DeriveInput) -> Result<proc_macro2::TokenStream, syn::Error> {
    let name = &input.ident;
    let raw_name = format_ident!("{name}Raw");

    if !input.generics.params.is_empty() {
        return Err(syn::Error::new_spanned(
            &input.generics,
            "SpecRaw supports only non-generic enums",
        ));
    }
    let Data::Enum(data) = &input.data else {
        return Err(syn::Error::new_spanned(&input, "SpecRaw expects an enum"));
    };

    let mut raw_variants = Vec::new();
    let mut from_arms = Vec::new();
    for variant in &data.variants {
        let v_ident = &variant.ident;
        let v_attrs = serde_attrs(&variant.attrs);
        match &variant.fields {
            Fields::Unit => {
                raw_variants.push(quote! { #(#v_attrs)* #v_ident });
                from_arms.push(quote! { #raw_name::#v_ident => #name::#v_ident });
            }
            Fields::Unnamed(unnamed) => {
                let fields: Vec<_> = unnamed
                    .unnamed
                    .iter()
                    .map(|f| {
                        let f_attrs = serde_attrs(&f.attrs);
                        let ty = &f.ty;
                        quote! { #(#f_attrs)* #ty }
                    })
                    .collect();
                let binds: Vec<_> = (0..unnamed.unnamed.len())
                    .map(|i| format_ident!("f{i}"))
                    .collect();
                raw_variants.push(quote! { #(#v_attrs)* #v_ident( #(#fields),* ) });
                from_arms.push(quote! {
                    #raw_name::#v_ident( #(#binds),* ) => #name::#v_ident( #(#binds),* )
                });
            }
            Fields::Named(named) => {
                let fields: Vec<_> = named
                    .named
                    .iter()
                    .map(|f| {
                        let f_attrs = serde_attrs(&f.attrs);
                        let ident = f.ident.as_ref().expect("named field");
                        let ty = &f.ty;
                        quote! { #(#f_attrs)* #ident: #ty }
                    })
                    .collect();
                let idents: Vec<_> = named
                    .named
                    .iter()
                    .map(|f| f.ident.clone().expect("named field"))
                    .collect();
                raw_variants.push(quote! { #(#v_attrs)* #v_ident { #(#fields),* } });
                from_arms.push(quote! {
                    #raw_name::#v_ident { #(#idents),* } => #name::#v_ident { #(#idents),* }
                });
            }
        }
    }

    Ok(quote! {
        // Same shape as the host enum, with derived externally-tagged
        // deserialization — used inside the host's `TryFrom` once bare-string
        // / tagged shapes are normalised. Generated by `#[derive(SpecRaw)]`;
        // unknown keys are a typo, not something to ignore, hence
        // `deny_unknown_fields`.
        #[derive(Debug, ::serde::Deserialize)]
        #[serde(rename_all = "snake_case")]
        #[serde(deny_unknown_fields)]
        #[allow(clippy::large_enum_variant)]
        #[doc(hidden)]
        enum #raw_name {
            #(#raw_variants),*
        }

        #[automatically_derived]
        impl ::core::convert::From<#raw_name> for #name {
            fn from(v: #raw_name) -> Self {
                match v {
                    #(#from_arms),*
                }
            }
        }
    })
}
