"""The shipped type stubs must describe the module that is actually built.

`python/fugazi/*.pyi` are generated by `tools/gen_python_stubs.py` from the
compiled extension, and committed. Nothing at run time reads them, so they drift
silently: a renamed parameter, a new keyword-only boundary or a whole new binding
would leave every consumer's type checker describing last release's API.

So this regenerates into a scratch directory and diffs. A failure means one of:

* a binding changed and the stub was not regenerated — run the generator;
* a *new* binding appeared that the generator cannot type — it says which, and
  the fix is a line in `RETURNS` / `MEMBER_RETURNS` / `MEMBER_RULES`.

The generator writes in place, so the diff runs against a copy of the tree.
"""

from __future__ import annotations

import pathlib
import shutil
import subprocess
import sys

import pytest

import fugazi as ta

ROOT = pathlib.Path(__file__).resolve().parent.parent
REPO = ROOT.parent
GENERATOR = REPO / "tools" / "gen_python_stubs.py"
STUB_DIR = ROOT / "fugazi"
STUBS = ("__init__.pyi", "metrics.pyi", "montecarlo.pyi")


def test_py_typed_marker_is_present():
    """Without it, PEP 561 says the stubs are not to be used — a checker ignores
    the whole package and every annotation above is dead weight."""
    assert (STUB_DIR / "py.typed").exists()


@pytest.mark.parametrize("name", STUBS)
def test_stub_exists_and_is_generated(name):
    text = (STUB_DIR / name).read_text()
    assert "GENERATED" in text, f"{name} lost its generated-file header"


def test_stubs_match_the_built_module(tmp_path):
    if not GENERATOR.exists():
        pytest.skip("generator not present in this checkout")

    # The generator writes to `<repo>/python/fugazi/`. Point it at a copy so the
    # committed files are never touched by a test run.
    sandbox = tmp_path / "repo"
    (sandbox / "python" / "fugazi").mkdir(parents=True)
    (sandbox / "tools").mkdir()
    shutil.copy(GENERATOR, sandbox / "tools" / GENERATOR.name)

    result = subprocess.run(
        [sys.executable, str(sandbox / "tools" / GENERATOR.name)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        "the stub generator refused to run:\n" + result.stderr
    )

    for name in STUBS:
        fresh = (sandbox / "python" / "fugazi" / name).read_text()
        committed = (STUB_DIR / name).read_text()
        assert fresh == committed, (
            f"python/fugazi/{name} is stale — the built module no longer matches "
            "the committed stub. Regenerate with:\n\n"
            "    python tools/gen_python_stubs.py\n"
        )


def test_every_public_name_appears_in_the_stub():
    """The cheap guard the diff above cannot be: it proves the *generator* is
    deterministic, this proves the *stub* covers the surface. A name reachable
    from `import fugazi` but absent from the stub is invisible to a checker."""
    stub = (STUB_DIR / "__init__.pyi").read_text()
    missing = [
        name
        for name in ta.__all__
        if not name.startswith("_")
        and f"class {name}" not in stub
        and f"def {name}(" not in stub
        and f"{name}:" not in stub
    ]
    assert not missing, f"public names absent from __init__.pyi: {sorted(missing)}"


def test_stubs_are_valid_types(tmp_path):
    """Staleness is one failure mode; *nonsense* is the other. The diff above
    proves the stub matches the module, not that what it says type-checks — a
    generator change could emit a forward reference to a class that no longer
    exists and the diff would happily agree with itself."""
    pytest.importorskip("mypy")
    result = subprocess.run(
        [sys.executable, "-m", "mypy", "--strict", "--cache-dir", str(tmp_path),
         *(str(STUB_DIR / name) for name in STUBS)],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    assert result.returncode == 0, (
        "the shipped stubs do not type-check:\n" + result.stdout + result.stderr
    )
